http://api.somafm.com/7soul130.pls
http://api.somafm.com/bagel130.pls
http://api.somafm.com/beatblender130.pls
http://api.somafm.com/bootliquor130.pls
http://api.somafm.com/brfm130.pls
http://api.somafm.com/cliqhop130.pls
http://api.somafm.com/covers130.pls
http://api.somafm.com/deepspaceone130.pls
http://api.somafm.com/defcon130.pls
http://api.somafm.com/digitalis130.pls
http://api.somafm.com/dronezone130.pls
http://api.somafm.com/dubstep130.pls
http://api.somafm.com/fluid130.pls
http://api.somafm.com/folkfwd130.pls
http://api.somafm.com/groovesalad130.pls
http://api.somafm.com/gsclassic130.pls
http://api.somafm.com/illstreet130.pls
http://api.somafm.com/indiepop130.pls
http://api.somafm.com/live130.pls
http://api.somafm.com/lush130.pls
http://api.somafm.com/missioncontrol130.pls
http://api.somafm.com/poptron130.pls
http://api.somafm.com/secretagent130.pls
http://api.somafm.com/seventies130.pls
http://api.somafm.com/sf1033130.pls
http://api.somafm.com/sonicuniverse130.pls
http://api.somafm.com/spacestation130.pls
http://api.somafm.com/suburbsofgoa130.pls
http://api.somafm.com/thetrip130.pls
http://api.somafm.com/thistle130.pls
http://api.somafm.com/u80s130.pls
http://api.somafm.com/metal130.pls
http://api.somafm.com/reggae130.pls
http://api.somafm.com/scanner130.pls
http://api.somafm.com/vaporwaves130.pls
http://api.somafm.com/specials130.pls
http://api.somafm.com/n5md130.pls
http://api.somafm.com/synphaera130.pls
